/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package pila;

import static java.lang.Thread.sleep;

/**
 *
 * @author alepd
 */
public class PilaApp extends java.awt.Frame {

    /**
     * Creates new form PilaApp
     */
    public PilaApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        final int ancho = 800, alto = 450;

        PilaApp frame = new PilaApp();
        VistaCanvas vista = new VistaCanvas(ancho, alto);

        frame.setSize(ancho, alto);
        frame.setLocation(375, 220);
        //elframe.setBackground(Color.red);
        frame.add(vista);

        frame.setVisible(true);

        Pila pila = new Pila(6, vista);

        Productor hp1 = new Productor(pila);
        Productor hp2 = new Productor(pila);
        Productor hp3 = new Productor(pila);
        Productor hp4 = new Productor(pila);

        Consumidor c = new Consumidor(pila);
        Thread hc1 = new Thread(c);

        hp1.start();
        hp2.start();
        hp3.start();
        hp4.start();
        hc1.start();

       hc1.join();
        System.out.println("Fin consumidor");
      
/*
        sleep(3000);
        for (int i = 0; i < 3; i++) {
            synchronized (pila) {
                pila.notifyAll();
            }
            sleep(200);
            System.out.println("Notica la main");
        }
  */      hp1.join();
        hp2.join();
        hp2.join();
        hp3.join();

        Thread.sleep(2000);
        System.exit(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
